# SPDX-FileCopyrightText: © 2020 Matt Williams <matt@milliams.com>
# SPDX-License-Identifier: MIT

name: Run tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry
      - name: Setup package
        run: poetry install -E azure -E google -E oracle
      - name: Run flake8
        run: poetry run flake8
      - name: Run mypy
        run: poetry run mypy mebula tests
      - name: Run black
        run: poetry run black --check .
      - name: Run pytest
        run: poetry run coverage run --source=mebula -m pytest --doctest-modules
      - name: Report coverage
        run: poetry run coverage report
      - name: Install resuse
        run: pip install reuse
      - name: Check REUSE spec
        run: reuse lint
      - name: Test that package builds
        run: poetry build
