name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Create Release ${{ github.ref }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          # body:  # TODO Read this from the CHANGELOG
          draft: false
          prerelease: false
      - name: Set PyPI credentials
        run: poetry config pypi-token.pypi ${PYPI_TOKEN}
        env:
          PYPI_TOKEN: ${{ secrets.pypi_token }}
      - name: Publish
        run: poetry publish
